# Generated by Django 3.2.3 on 2021-06-07 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_semester', models.CharField(max_length=20)),
                ('class_id', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=20)),
                ('class_time', models.CharField(max_length=20)),
                ('class_credit', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=10)),
                ('college_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWEB.college')),
            ],
        ),
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWEB.class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWEB.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('man', '男'), ('woman', '女')], max_length=10)),
                ('age', models.IntegerField(max_length=10)),
                ('college_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWEB.college')),
            ],
        ),
        migrations.CreateModel(
            name='Select',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWEB.class')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWEB.student')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_semester', models.CharField(max_length=20)),
                ('usual_score', models.FloatField(blank=True)),
                ('test_score', models.FloatField(blank=True)),
                ('final_score', models.FloatField(blank=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWEB.class')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWEB.student')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWEB.teacher')),
            ],
        ),
    ]
