# Generated by Django 3.2.3 on 2021-06-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_time',
            field=models.TimeField(max_length=20),
        ),
    ]
