# Generated by Django 3.2.3 on 2021-06-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0003_rename_class_name_select_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(),
        ),
    ]
