# Generated by Django 3.2.3 on 2021-06-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0004_auto_20210607_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoretable',
            old_name='teacher_name',
            new_name='teacher_id',
        ),
        migrations.AlterField(
            model_name='class',
            name='class_credit',
            field=models.IntegerField(),
        ),
    ]
